name: Clean install and build check (no deploy) with specified content

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy_with_NEBULA:
    permissions: 
      contents: write
    uses: ./.github/workflows/deploy.yml
    with:
      content_organization: esciencecenter-digital-skills
      content_repository: NEBULA-content-template
      content_ref: v1.1.0
      base_url: NEBULA
      nebula_ref: ${{ github.sha }}
      deploy_to_ghpages: false
