name: Base NEBULA deployment reusable workflow

on:
  workflow_call:
    inputs:
      content_organization: 
        required: true
        type: string
      content_repository: 
        required: true
        type: string
      content_ref: 
        required: true
        type: string
      nebula_ref:
        required: true
        type: string
      base_url:
        required: false
        type: string
      deploy_to_ghpages: 
        description: 'Deploys to gh-pages branch if set to true (default). Set this to false for testing builds/generation.'
        required: false
        default: true
        type: boolean
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Print inputs
        run: |
          echo content_organization: ${{ inputs.content_organization }}
          echo content_repository: ${{ inputs.content_repository }}
          echo content_ref: ${{ inputs.content_ref }}
          echo nebula_ref: ${{ inputs.nebula_ref }}
          echo base_url: ${{ inputs.base_url }}
          echo deploy_to_ghpages: ${{ inputs.deploy_to_ghpages }}

      - name: Checkout content
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.content_organization }}/${{ inputs.content_repository }}
          ref: ${{ inputs.content_ref }}
          path: ./${{ inputs.content_repository }}
      
      - name: Set content path environment variable
        run: echo "CONTENT_PATH=${PWD}/${{ inputs.content_repository }}" >> $GITHUB_ENV

      - name: Set base url environment variable
        if: "${{ inputs.base_url != '' }}"
        run: |
          echo "BASE_URL=${{ inputs.base_url }}" >> $GITHUB_ENV
          echo "The base url in config.json will be overwritten with ${{ inputs.base_url }}"

      - name: Checkout NEBULA framework
        uses: actions/checkout@v4
        with:
          repository: esciencecenter-digital-skills/NEBULA
          ref: ${{ inputs.nebula_ref }}
          path: ./NEBULA

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-

      - name: Install dependencies
        run: |
          cd NEBULA
          npm ci

      - name: Generate
        run: |
          export NEBULA_PRERENDER=TRUE
          cd NEBULA
          npx nuxi generate

      - name: Deploy
        if: ${{ inputs.deploy_to_ghpages }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./NEBULA/.output/public
